name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: --health-cmd="pg_isready -U user -d test_db" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m venv .vmems
        source .vmems/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-flask  # Ensure pytest is installed

    - name: Install PostgreSQL client
      run: sudo apt-get install -y postgresql-client

    - name: Wait for PostgreSQL to be ready
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        until pg_isready -h localhost -p 5432 -U user -d test_db; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 1
        done

    - name: Run tests
      env:
        DATABASE_URL: postgres://user:password@localhost:5432/test_db
      run: |
        source .vmems/bin/activate
        pytest --maxfail=5 --disable-warnings -v
